version: 2
 
sources:
  - name: raw_qwt
    database: QWT_ANALYTICS_DEV
    schema: RAW
    tables:
      - name: CUSTOMERS
      - name: Products
      - name: Orders
      - name: OrderDetails
      - name: employee
      - name: OFFICES
      - name: Shipments
      - name: Suppliers